name: plo.ug
description: "Infrequent musings"
meta_description: "Infrequent musings"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: '/'
domain_name: 'http://plo.ug'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'plo.ug'
author:         'Per Ploug'
